spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradesystem
    username: root
    password: 2627


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

jwt:
  secret: 71711f3c5e1b9079ab16f833226cd12027a50a8110b2a8054f1eaf09383b2f7d
