spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:gradesystem}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:9090}

jwt:
  secret: ${JWT_SECRET:defaultsecret}
