spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true   # <-- uses dash, not underscore
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers, beans, env, info

server:
  port: ${SERVER_PORT}
